version: "3.8"
services:
  nginx:
    depends_on:
      - php-fpm
    restart: always
    container_name: ${PROJECT_NAME}-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend:/www
    ports:
      - "${SSL_EXTERNAL_PORT}:443"
      - "${HTTP_EXTERNAL_PORT}:80"
    networks:
      app:
        aliases:
          - nginx
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
  php-fpm:
    restart: always
    container_name: ${PROJECT_NAME}-php-fpm
    environment:
      PHP_IDE_CONFIG: serverName=yii2
    volumes:
      - ./backend:/www
      - ./php/php.ini:/usr/local/lib/php.ini
      - ./php/xdebug.ini:/usr/local/lib/conf.d/xdebug.ini
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      app:
        aliases:
          - php-fpm
    build:
      context: ./
      dockerfile: ./php/Dockerfile
networks:
  app:
    name: "${PROJECT_NAME}-app"
